name: CD

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy DEV
        run: "curl ${{ secrets.RENDER_DEPLOY_HOOK_DEV }}"

  deploy-qa:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy QA
        run: "curl ${{ secrets.RENDER_DEPLOY_HOOK_QA }}"

  deploy-prd:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy PRD
        run: "curl ${{ secrets.RENDER_DEPLOY_HOOK_PRD }}"